run:
  concurrency: 4
  deadline: 1m
  issues-exit-code: 1
  tests: true


# output configuration options
output:
  # colored-line-number|line-number|json|tab|checkstyle, default is "colored-line-number"
  format: colored-line-number
  print-issued-lines: false
  print-linter-name: true


linters:
  enable-all: true
  disable:
    - maligned
    - prealloc
    - gosec
    - lll


issues:
  exclude-use-default: false
  max-per-linter: 0
  max-same-issues: 0
